In [3]:
import pandas as pd

File = 'swiggy.csv'

df = pd.read_csv(File)

df.head(5)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [ ]:
# How many rows?
len(df)
# What columns exist?
df.columns

# Any missing values?
df.isnull().sum()

# Data types correct? (date, numbers)
df.info()

In [4]:
# Top 5 Restaurants by rating

df.sort_values(by='Avg ratings', ascending=False).head(5)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
5424,427280,Chembur,Mumbai,Get In My Belly,500.0,5.0,20,Indian,Chembur,58
5425,427282,Chembur,Mumbai,The Asian Pavilion,200.0,5.0,20,Asian Chinese,Chembur,64
5519,431996,Scruz Bandra East,Mumbai,Cafe Kokomo,400.0,5.0,50,"Beverages,Snacks,Desserts,Bakery",Scruz Bandra East,46
8571,450543,Perambur,Chennai,Afresh,100.0,5.0,20,"Healthy Food,Salads,Desserts,Beverages",Perambur,50
6297,458258,Nsp,Delhi,Fat Tiger,300.0,5.0,20,"Pizzas,Chinese,Snacks,Beverages,American",Nsp,73

In [7]:
# Top 5 by popularity
df.sort_values(by='Total ratings', ascending=False).head(5)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
1819,131870,Kavadiguda,Hyderabad,4M Biryani House,250.0,4.1,10000,"Biryani,North Indian,Chinese",Nallakunta & Vidyanagar,41
90,4138,Koti,Hyderabad,Grand Hotel,300.0,4.1,10000,"Biryani,Tandoor,Chinese,Indian,Kebabs,Desserts",Abids Road,24
803,34634,Toli Chowki,Hyderabad,Shah Ghouse Cafe & Restaurant,350.0,4.0,10000,Biryani North Indian Chinese Mughlai Tandoor,Tolichowki,63
4069,367769,Chintal,Hyderabad,Lucky Restaurant,300.0,4.0,10000,"Biryani,Tandoor,Chinese,North Indian,Desserts,...",Banjara Hills,38
95,4320,Narayanguda,Hyderabad,Mehfil,300.0,3.9,10000,"Biryani,Tandoor,Chinese,Indian,Kebabs,Desserts",Narayanguda,25

In [8]:
# Avg delivery time per city
df.groupby('City')['Delivery time'].mean()

City
Ahmedabad    44.709902
Bangalore    50.529598
Chennai      58.968354
Delhi        50.734861
Hyderabad    49.933023
Kolkata      67.809807
Mumbai       48.318716
Pune         55.854128
Surat        48.484375
Name: Delivery time, dtype: float64

In [10]:
# sort by avg rating , total ratings values
best_restaurants = df.sort_values(by=['Avg ratings', 'Total ratings'], ascending=[False, False]).head(5)
best_restaurants

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
5519,431996,Scruz Bandra East,Mumbai,Cafe Kokomo,400.0,5.0,50,"Beverages,Snacks,Desserts,Bakery",Scruz Bandra East,46
3894,357553,Bandra East,Mumbai,Diamond Market Pizza Jp,600.0,5.0,20,Italian,Scruz Bandra East,43
5424,427280,Chembur,Mumbai,Get In My Belly,500.0,5.0,20,Indian,Chembur,58
5425,427282,Chembur,Mumbai,The Asian Pavilion,200.0,5.0,20,Asian Chinese,Chembur,64
5684,438198,Kothrud,Pune,Papacream,350.0,5.0,20,Ice Cream,Kothrud,52

In [13]:
# Top 5 city by avg rating and total ratings

city_analysis = df.groupby('City').agg({'Avg ratings' : 'mean', 'Total ratings': 'mean'}).reset_index()

city_analysis = city_analysis.sort_values(by=['Avg ratings', 'Total ratings'], ascending=[False , False])
city_analysis.head(5)

        City  Avg ratings  Total ratings
2    Chennai     3.776311     161.717902
1  Bangalore     3.762896     148.520085
4  Hyderabad     3.701395     307.227907
5    Kolkata     3.698811     163.298663
6     Mumbai     3.599374     118.214565

In [49]:
# Top Restaurant by City
top_restaurant = df.groupby(['City', 'Restaurant']).agg({'Avg ratings': 'mean', 'Total ratings': 'sum'}).reset_index()
top_restaurant = top_restaurant.sort_values(by=['Avg ratings', 'Total ratings'], ascending=[False , False]).groupby('City').head(1)
top_restaurant

,City,Restaurant,Avg ratings,Total ratings
5894,Mumbai,Cafe Kokomo,5.0,50
922,Bangalore,Creams & Bites,5.0,20
1670,Chennai,Afresh,5.0,20
2915,Delhi,Fat Tiger,5.0,20
4167,Hyderabad,Splurge - Thickshakes And Milkshakes,5.0,20
5023,Kolkata,Keventers Ice Creamery,5.0,20
7650,Pune,Papacream,5.0,20
419,Ahmedabad,Natural Ice Cream,4.8,100
8269,Surat,Kudrati Kahumbo,4.8,50

In [21]:
df.groupby('Restaurant')['Total ratings'].sum().sort_values(ascending=False)

Restaurant
Shah Ghouse Cafe & Restaurant           15000
Mehfil                                  10160
Lucky Restaurant                        10020
Bawarchi                                10000
Grand Hotel                             10000
                                        ...
Sai Krupa Sandwiches & Snacks Centre       20
Sai Datta Andhra Mess                      20
Sai Baba Idli Dhosa Center                 20
Cafe Alvi                                  20
Healing Rice Bowls                         20
Name: Total ratings, Length: 7865, dtype: int64

In [34]:
# Unique Restaurants count by city
unique_restaurants = df.groupby('City')['Restaurant'].nunique()
unique_restaurants

City
Ahmedabad     709
Bangalore     938
Chennai      1096
Delhi         611
Hyderabad    1030
Kolkata      1325
Mumbai       1253
Pune         1080
Surat         505
Name: Restaurant, dtype: int64

In [57]:
# Top 3 restaurants per city
top_3_restaurant_by_city = df.groupby(['City', 'Restaurant']).agg({'Avg ratings': 'mean', 'Total ratings': 'sum'}).reset_index()
top_3_restaurant_by_city = top_3_restaurant_by_city.sort_values(by=['City', 'Avg ratings', 'Total ratings'] , ascending=[True,  False, False]).groupby('City').head(3)
top_3_restaurant_by_city

,City,Restaurant,Avg ratings,Total ratings
419,Ahmedabad,Natural Ice Cream,4.8,100
699,Ahmedabad,Wok On Fire - Indo Chinese - Pan Asian,4.8,50
144,Ahmedabad,Ching Chong Chinese,4.8,20
922,Bangalore,Creams & Bites,5.0,20
1589,Bangalore,Tricky Shakes,5.0,20
990,Bangalore,Frosty Crumble,4.9,20
1670,Chennai,Afresh,5.0,20
1648,Chennai,1By2,4.9,20
2276,Chennai,Milkie Mustache,4.9,20
2915,Delhi,Fat Tiger,5.0,20
2787,Delhi,Biryani By Kilo,4.8,20
3149,Delhi,Pizza Paradise By Vhc,4.8,20
4167,Hyderabad,Splurge - Thickshakes And Milkshakes,5.0,20
4296,Hyderabad,The Liege Waffles,5.0,20
4364,Hyderabad,Wallonia Waffle Co.,5.0,20
5023,Kolkata,Keventers Ice Creamery,5.0,20
5257,Kolkata,Pabrai'S Fresh And Naturelle Icecream,4.9,20
5219,Kolkata,Nic Natural Ice Creams,4.8,500
5894,Mumbai,Cafe Kokomo,5.0,50
6026,Mumbai,Diamond Market Pizza Jp,5.0,20
6111,Mumbai,Get In My Belly,5.0,20
7650,Pune,Papacream,5.0,20
7803,Pune,Shree Krishna Juice Bar,5.0,20
7301,Pune,Gulp,4.9,20
8269,Surat,Kudrati Kahumbo,4.8,50
8468,Surat,Sobis Diet Farm,4.8,50
8515,Surat,The Pancake Story,4.8,20