In [2]:
import pandas as pd

files = 'food_delivery_dataset.csv'

df = pd.read_csv(files)

df.head(5)

,order_id,user_id,city,restaurant_name,order_value,discount,final_amount,delivery_time,order_date,payment_method
0,1,1276,Delhi,Pizza Palace,727.40,20.66,706.74,20,2024-01-18,Card
1,2,1184,Delhi,Pizza Palace,770.54,86.04,684.50,47,2024-05-23,Cash
2,3,1077,Mumbai,Cafe Coffee,142.00,73.53,68.47,42,2024-01-27,UPI
3,4,1283,Pune,Biryani House,452.68,71.99,380.69,32,2024-01-10,UPI
4,5,1055,Pune,Cafe Coffee,328.89,85.74,243.15,37,2024-05-09,UPI

In [ ]:
# Average Order Frequency

average_order_frequency = len(df) / df['user_id'].nunique()
print(average_order_frequency)

5.0352467270896275

In [12]:
#  Repeat customer %
customers_orders = df.groupby('user_id')['order_id'].count().reset_index(name='orders')
repeat_customers = (len(customers_orders[customers_orders['orders'] > 1]) / customers_orders['user_id'].count())* 100
repeat_customers

np.float64(95.9718026183283)

In [ ]:
# Top 10 users contribution to revenue by orders
top_contribution = df.groupby('user_id').agg({'order_id': 'count', 'final_amount': 'sum'}).sort_values(by='final_amount', ascending=False)
top_contribution.head(10)

         order_id  final_amount
user_id
1177           13       5936.54
1471           11       5328.14
1891           10       5254.18
1661           11       5211.93
1467           10       4926.18
1890           11       4907.92
1733           10       4685.17
1081           10       4676.69
1162           11       4644.66
1603            9       4637.13

In [ ]:
# Top 10% users contribution to revenue

user_revenue = df.groupby('user_id')['final_amount'].sum().sort_values(ascending=False)

top_10_percent = int(len(user_revenue) * 0.1)
top_users = user_revenue.head(top_10_percent)


top_contribution = top_users.sum() / user_revenue.sum() * 100

top_contribution

np.float64(19.473870759620706)

In [44]:
# Revenue from repeat vs new users
user_orders = df.groupby('user_id')['order_id'].count()

repeat_customers = user_orders[user_orders > 1].index

df['user_type'] = df['user_id'].apply(lambda x: 'repeat' if x in repeat_customers else 'new')

# revenue_split = df.groupby('user_type')['final_amount'].sum()
# revenue_split_percentage = revenue_split / revenue_split.sum() * 100
# revenue_split_percentage 

revenue_split = df.groupby('user_type')['final_amount'].sum()
revenue_split

revenue_percentage = revenue_split / revenue_split.sum() * 100
revenue_percentage

user_type
new        0.771836
repeat    99.228164
Name: final_amount, dtype: float64